apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-zfs
parameters:
  recordsize: "4k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "raid/enc"
provisioner: zfs.csi.openebs.io
